mysql:
  host: 127.0.0.1
  port: 30543
  user: postgres
  password: 123456
  database: authentication

postgres:
  host: 127.0.0.1
  port: 30543
  user: postgres
  password: 123456
  database: authentication

server:
  port: 3000
  mode: debug # release or debug

jwt:
  issuer: "local-app"
  user_access_token_key: "1505440689"
  user_refresh_token_key: "0790673021"
